# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='teacher_csvs', verbose_name='Teacher CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm giáo viên từ file CSV',
                'verbose_name_plural': 'Thêm giáo viên từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='do_an',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên đồ án')),
                ('slug_name', models.SlugField(null=True, unique=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Đồ án',
                'verbose_name_plural': 'Đồ án',
            },
        ),
    ]
