# Generated by Django 3.2.8 on 2022-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_student_year_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='do_an',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên đồ án')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('student', models.ManyToManyField(related_name='do_an_tham_gia', to='users.Student', verbose_name='Sinh viên')),
                ('teacher', models.ManyToManyField(related_name='do_an_tham_gia', to='users.Teacher', verbose_name='Giáo viên')),
            ],
        ),
    ]
