# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='do_an',
            name='student',
            field=models.ManyToManyField(related_name='do_an_tham_gia', to='users.Student', verbose_name='Sinh viên'),
        ),
        migrations.AddField(
            model_name='do_an',
            name='teacher',
            field=models.ManyToManyField(related_name='do_an_tham_gia', to='users.Teacher', verbose_name='Giáo viên'),
        ),
    ]
