# Generated by Django 3.2.8 on 2022-01-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_do_an_slug_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='do_an',
            options={'verbose_name': 'Đồ án', 'verbose_name_plural': 'Đồ án'},
        ),
    ]
