# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Avatar', verbose_name='Ảnh đại diện')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='Email')),
                ('firstname', models.CharField(max_length=20, null=True, verbose_name='Tên')),
                ('surname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tên đệm')),
                ('lastname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Họ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50, verbose_name='Gender')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('year_start', models.IntegerField(default=2015, verbose_name='Năm bắt đầu công tác')),
                ('chuyen_mon', models.ManyToManyField(related_name='giao_vien_theo_chuyen_mon', to='management.hoc_phan', verbose_name='Học phần')),
                ('vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_giao_vien', to='management.vien_dao_tao', verbose_name='Viện')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('year_start', models.IntegerField(default=2022, verbose_name='Năm vào trường')),
                ('code', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Mã số sinh viên')),
                ('khoa', models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.khoa', verbose_name='Khóa')),
                ('lop_chung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinh_vien', to='management.lop_chung', verbose_name='Lớp chung')),
                ('vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.vien_dao_tao', verbose_name='Viện')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
            },
            bases=('users.user',),
        ),
    ]
