# Generated by Django 3.2.8 on 2022-01-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_sinhvien_loptinchidetail_loptinchidetail'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lop_tin_chi_dang_ki',
            field=models.ManyToManyField(related_name='sinh_vien_trong_lop_tin_chi', to='student.lop_tin_chi_detail', verbose_name='Lớp tín chỉ đăng kí'),
        ),
    ]
