# Generated by Django 3.2.8 on 2022-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_lop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_start',
            field=models.IntegerField(default=2022, verbose_name='Năm vào trường'),
        ),
    ]
