# Generated by Django 3.2.8 on 2022-01-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_hoc_phan_sinh_vien'),
        ('users', '0003_alter_student_year_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='chuyen_mon',
            field=models.ManyToManyField(related_name='giao_vien_theo_chuyen_mon', to='management.hoc_phan', verbose_name='Học phần'),
        ),
    ]
