# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_hocPhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='hocphan_csv', verbose_name='Học phần CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm học phần từ file CSV',
                'verbose_name_plural': 'Thêm học phần từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='csv_semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='semester_csv', verbose_name='Semester CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm kì học từ file CSV',
                'verbose_name_plural': 'Thêm kì học từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='csv_vienDaoTao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='hocphan_csv', verbose_name='Học phần CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm viện đào tạo từ file CSV',
                'verbose_name_plural': 'Thêm viện đào tạo từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='csvTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='quanLy_csvs', verbose_name='Timetable CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm thời khóa biểu từ file CSV',
                'verbose_name_plural': 'Thêm thời khóa biểu từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='csvTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='quanLy_csvs', verbose_name='TimingCSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm thời gian từ file CSV',
                'verbose_name_plural': 'Thêm thời gian từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='csvWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='quanLy_csvs', verbose_name='Week CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm tuần học từ file CSV',
                'verbose_name_plural': 'Thêm tuần học từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='hoc_phan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên học phần')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã học phần')),
            ],
            options={
                'verbose_name': '2. Học phần',
                'verbose_name_plural': '2. Học phần',
                'ordering': ['vien'],
            },
        ),
        migrations.CreateModel(
            name='khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='Khóa')),
            ],
            options={
                'verbose_name': '3. Khóa',
                'verbose_name_plural': '3. Khóa',
            },
        ),
        migrations.CreateModel(
            name='lop_chung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Tên lớp')),
            ],
            options={
                'verbose_name': '5. Lớp chung',
                'verbose_name_plural': '5. Lớp chung',
            },
        ),
        migrations.CreateModel(
            name='lop_tin_chi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Mã lớp')),
                ('type', models.CharField(choices=[('Lý thuyết', 'LT'), ('Thí nghiệm', 'TN'), ('Lí thuyết + Bài tập', 'LT+BT')], default='Lý thuyết', max_length=20, verbose_name='Loại lớp')),
            ],
            options={
                'verbose_name': 'Lớp tín chỉ',
                'verbose_name_plural': 'Lớp tín chỉ',
            },
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, validators=[management.validators.validate_semester], verbose_name='Kì')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '4. Kì',
                'verbose_name_plural': '4. Kì',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
            ],
            options={
                'verbose_name': '8. Thời khóa biểu',
                'verbose_name_plural': '8. Thời khóa biểu',
            },
        ),
        migrations.CreateModel(
            name='timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Thời gian bắt đầu')),
                ('time_end', models.TimeField(verbose_name='Thời gian kết thúc')),
            ],
            options={
                'verbose_name': '6. Thời gian',
                'verbose_name_plural': '6. Thời gian',
            },
        ),
        migrations.CreateModel(
            name='vien_dao_tao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên viện')),
                ('code', models.CharField(max_length=10, verbose_name='Mã viện')),
            ],
            options={
                'verbose_name': 'Viện đào tạo',
                'verbose_name_plural': '1. Viện đào tạo',
            },
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tuần')),
            ],
            options={
                'verbose_name': '7. Tuần',
                'verbose_name_plural': '7. Tuần',
            },
        ),
    ]
