# Generated by Django 3.2.8 on 2021-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hoc_phan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên học phần')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã học phần')),
            ],
            options={
                'verbose_name': 'Học phần',
                'verbose_name_plural': 'Học phần',
                'ordering': ['vien'],
            },
        ),
        migrations.CreateModel(
            name='khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='Khóa')),
            ],
            options={
                'verbose_name': 'Khóa',
                'verbose_name_plural': 'Khóa',
            },
        ),
        migrations.CreateModel(
            name='lop_chung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Tên lớp')),
            ],
            options={
                'verbose_name': 'Lớp chung',
                'verbose_name_plural': 'Lớp chung',
            },
        ),
        migrations.CreateModel(
            name='vien_dao_tao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên viện')),
                ('code', models.CharField(max_length=10, verbose_name='Mã viện')),
            ],
            options={
                'verbose_name': 'Viện đào tạo',
                'verbose_name_plural': 'Viện đào tạo',
            },
        ),
    ]
