# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vien_dao_tao',
            name='vien_truong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vien_quan_ly', to='users.teacher', verbose_name='Viện trưởng'),
        ),
        migrations.AlterUniqueTogether(
            name='timing',
            unique_together={('time_start', 'time_end')},
        ),
        migrations.AddField(
            model_name='timetable',
            name='week',
            field=models.ManyToManyField(to='management.week'),
        ),
        migrations.AddField(
            model_name='lop_tin_chi',
            name='hocPhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_class', to='management.hoc_phan', verbose_name='Học phần'),
        ),
        migrations.AddField(
            model_name='lop_chung',
            name='giao_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_lop_quan_ly', to='users.teacher', verbose_name='Giáo viên quản lý'),
        ),
        migrations.AddField(
            model_name='lop_chung',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lop_cung_khoa', to='management.khoa', verbose_name='Khóa'),
        ),
        migrations.AddField(
            model_name='lop_chung',
            name='vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_lop_thuoc_vien', to='management.vien_dao_tao', verbose_name='Viện quản lý'),
        ),
        migrations.AddField(
            model_name='hoc_phan',
            name='required_hocPhan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.hoc_phan', verbose_name='Học phần kiên quyết'),
        ),
        migrations.AddField(
            model_name='hoc_phan',
            name='vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_hoc_phan', to='management.vien_dao_tao', verbose_name='Viện trực thuộc'),
        ),
        migrations.AlterUniqueTogether(
            name='lop_chung',
            unique_together={('name', 'khoa')},
        ),
    ]
