# Generated by Django 3.2.8 on 2022-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_lopTinChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='hocphan_csv', verbose_name='Học phần CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thêm lớp tín chỉ từ file CSV',
                'verbose_name_plural': 'Thêm lớp tín chỉ từ file CSV',
            },
        ),
        migrations.AlterModelOptions(
            name='lop_tin_chi',
            options={'verbose_name': '9. Lớp tín chỉ', 'verbose_name_plural': '9. Lớp tín chỉ'},
        ),
    ]
