# Generated by Django 3.2.8 on 2021-12-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lop_chung',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lop_cung_khoa', to='management.khoa', verbose_name='Khóa'),
        ),
        migrations.AlterField(
            model_name='lop_chung',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Tên lớp'),
        ),
        migrations.AlterUniqueTogether(
            name='lop_chung',
            unique_together={('name', 'khoa')},
        ),
    ]
