# Generated by Django 3.2.8 on 2022-01-30 14:05

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_lop_tin_chi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.IntegerField(max_length=5, unique=True, validators=[management.validators.validate_semester], verbose_name='Kì'),
        ),
    ]
