# Generated by Django 3.2.8 on 2022-01-31 09:46

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.IntegerField(unique=True, validators=[management.validators.validate_semester], verbose_name='Kì'),
        ),
    ]
