# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models
import django.db.models.deletion
import student.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='student_csvs', verbose_name='Student CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Thêm sinh viên từ file CSV',
                'verbose_name_plural': 'Thêm sinh viên từ file CSV',
            },
        ),
        migrations.CreateModel(
            name='lop_tin_chi_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Lớp tín chỉ chi tiết',
                'verbose_name_plural': 'Lớp tín chỉ chi tiết',
            },
        ),
        migrations.CreateModel(
            name='sinhVien_lopTinChiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giua_ki', models.FloatField(blank=True, null=True, validators=[student.validators.validate_score], verbose_name='Điểm giữa kì')),
                ('cuoi_ki', models.FloatField(blank=True, null=True, validators=[student.validators.validate_score], verbose_name='Điểm cuối kì')),
                ('lopTinChiDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinhVien', to='student.lop_tin_chi_detail', verbose_name='Lớp tín chỉ')),
            ],
            options={
                'verbose_name': 'Bảng điểm',
                'verbose_name_plural': 'Bảng điểm',
            },
        ),
    ]
