# Generated by Django 3.2.8 on 2022-01-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('users', '0001_initial'),
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien_loptinchidetail',
            name='sinhVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lopTinChiThamGia', to='users.student', verbose_name='Sinh viên'),
        ),
        migrations.AddField(
            model_name='lop_tin_chi_detail',
            name='lopTinChi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.lop_tin_chi', verbose_name='Lớp tín chỉ'),
        ),
        migrations.AddField(
            model_name='lop_tin_chi_detail',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_class', to='management.semester', verbose_name='Kì'),
        ),
        migrations.AddField(
            model_name='lop_tin_chi_detail',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='lop_tin_chi_detail',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.timetable'),
        ),
        migrations.AddField(
            model_name='lop_tin_chi_detail',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.timing'),
        ),
        migrations.AlterUniqueTogether(
            name='sinhvien_loptinchidetail',
            unique_together={('sinhVien', 'lopTinChiDetail')},
        ),
    ]
