# Generated by Django 3.2.8 on 2021-12-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_initial'),
        ('users', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien_hocphan',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='lop',
            name='hoc_phan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_class', to='management.hoc_phan', verbose_name='Học phần'),
        ),
        migrations.AddField(
            model_name='lop',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='lop',
            name='timetable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.timetable'),
        ),
        migrations.AddField(
            model_name='lop',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.timing'),
        ),
        migrations.AlterUniqueTogether(
            name='sinhvien_hocphan',
            unique_together={('sinh_vien', 'hoc_phan', 'number')},
        ),
    ]
