# Generated by Django 3.2.8 on 2021-12-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Tuần'),
        ),
    ]
