# Generated by Django 3.2.8 on 2021-12-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211226_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien_hocphan',
            name='lop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.lop', verbose_name='Lớp đăng kí'),
        ),
    ]
