# Generated by Django 3.2.8 on 2022-01-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_lop_tin_chi_detail_loptinchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien_loptinchidetail',
            name='lopTinChiDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='student.lop_tin_chi_detail', verbose_name='Lớp tín chỉ'),
        ),
    ]
