# Generated by Django 3.2.8 on 2021-12-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_lop'),
        ('student', '0004_sinhvien_hocphan_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='lop',
            name='sinh_vien',
            field=models.ManyToManyField(blank=True, related_name='lopTC', to='users.Student', verbose_name='Sinh viên'),
        ),
    ]
