# Generated by Django 3.2.8 on 2021-12-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_lop'),
        ('student', '0005_lop_sinh_vien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lop',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
