# Generated by Django 3.2.8 on 2022-01-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_year_start'),
        ('student', '0008_alter_lop_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien_hocphan',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_diem', to='users.student', verbose_name='Sinh viên'),
        ),
    ]
