# Generated by Django 3.2.8 on 2022-01-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_sinhvien_hocphan_sinh_vien'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='student_csvs', verbose_name='Student CSV file')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded time')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
